name: Playwright Tests

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 * * *" # Every day on midnight (GMT+0)

jobs:
  Run_Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          pip install pytest pytest-playwright python-dotenv
          playwright install
      
      - name: Run tests
        env:
          HEADLESS: "true" 
          BROWSER: "chromium" 
          LOGIN_PAGE_URL: ${{ secrets.LOGIN_PAGE_URL }} 
        run: |
          cd tests 
          pytest login_tests.py 
          pytest end_to_end_tests.py
